@hostname = localhost
@port = 8130
@host = {{hostname}}:{{port}}
@contentType = application/json
@blogId = asdf1234

### Home

GET http://{{host}}/

### Post comment

POST http://{{host}}/api/comment/
Content-Type: {{contentType}}

{
  "blogId": "{{blogId}}",
  "authorName": "Hemuli",
  "content": "Testi-kommentti 123"
}

### Get comment by blogId

GET http://{{host}}/api/comment/
Content-Type: {{contentType}}

{
  "blogId": "{{blogId}}",
  "authorName": "Hemuli",
  "content": "Testi-kommentti 123"
}