http:
  port: 8050
  hostname: localhost
admin:
  port: 9876
  hostname: localhost

apiEndpoints:
  blogAPI:
    host: localhost
    paths: ['/api/blog','/api/blog/*']
  userAPI: 
    host: localhost
    paths: ['/api/user','/api/user/*', '/api/auth/*','/api/auth']
serviceEndpoints:
  blogservice:
    urls: 
    - 'http://localhost:8110/'
  userservice: 
    url: 'http://localhost:8120/'

policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - log
pipelines:
  blogs:
    apiEndpoints:
      - blogAPI
    policies:
      - log:
        - action:
            message: ${req.method} ${req.originalUrl}

      - proxy:
          - action:
              serviceEndpoint: blogservice 
              changeOrigin: true

  users:
    apiEndpoints:
      - userAPI
    policies:
      - log:
        - action:
            message: ${req.method} ${req.originalUrl}

      - proxy:
          - action:
              serviceEndpoint: userservice 
              changeOrigin: true
