version: '3'

services:
  mircroservice:
    image: userservice
    build: .
    environment:
      NODE_ENV: developement
    ports:
      - 777:777
      - 9229:9229
    ## set your startup file here
    command: node --inspect index.js